In [60]:
import numpy as np

from scipy.optimize import minimize as minimise
from scipy import optimize

In [61]:
F_ty = 400

In [62]:
K = 3.2

In [63]:
def capacity(x, F_ty, K):
    t = x[0]
    D = x[1]
    w = x[2]
    bending_capacity = (np.pi * D ** 3 * F_ty)/ (16 * t)
    bearing_capacity = K * F_ty * D * t
    section_capacity = F_ty * (w-D) * t
    # print(f'({bending_capacity}, {bearing_capacity}, {section_capacity})')
    return -min(bending_capacity, bearing_capacity, section_capacity)

In [64]:
rranges = (slice(0.00001, 10, 1), slice(0.00001, 15, 1), slice(0.00001, 15, 1))
result = optimize.brute(capacity, rranges, args=(F_ty, K), full_output=True,finish=None)
result

(array([ 7.00001, 10.00001, 14.00001]),
 np.float64(-11200.016),
 array([[[[1.000000e-05, 1.000000e-05, 1.000000e-05, ..., 1.000000e-05,
           1.000000e-05, 1.000000e-05],
          [1.000000e-05, 1.000000e-05, 1.000000e-05, ..., 1.000000e-05,
           1.000000e-05, 1.000000e-05],
          [1.000000e-05, 1.000000e-05, 1.000000e-05, ..., 1.000000e-05,
           1.000000e-05, 1.000000e-05],
          ...,
          [1.000000e-05, 1.000000e-05, 1.000000e-05, ..., 1.000000e-05,
           1.000000e-05, 1.000000e-05],
          [1.000000e-05, 1.000000e-05, 1.000000e-05, ..., 1.000000e-05,
           1.000000e-05, 1.000000e-05],
          [1.000000e-05, 1.000000e-05, 1.000000e-05, ..., 1.000000e-05,
           1.000000e-05, 1.000000e-05]],
 
         [[1.000010e+00, 1.000010e+00, 1.000010e+00, ..., 1.000010e+00,
           1.000010e+00, 1.000010e+00],
          [1.000010e+00, 1.000010e+00, 1.000010e+00, ..., 1.000010e+00,
           1.000010e+00, 1.000010e+00],
          [1.000010e+

In [65]:
result[0] 

array([ 7.00001, 10.00001, 14.00001])